# Generated by Django 5.2.6 on 2026-09-09 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RailwaySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("start_station", models.CharField(max_length=80)),
                ("end_station", models.CharField(max_length=80)),
                ("length", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESTRICTED", "Restricted"),
                            ("CLOSED", "Closed"),
                        ],
                        default="AVAILABLE",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("train_number", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("train_type", models.CharField(max_length=40)),
                ("priority", models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("asset_type", models.CharField(max_length=80)),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("GOOD", "Good"),
                            ("DUE", "Maintenance Due"),
                            ("CRITICAL", "Critical"),
                            ("UNAVAILABLE", "Unavailable"),
                        ],
                        max_length=16,
                    ),
                ),
                ("criticality", models.PositiveSmallIntegerField(default=3)),
                ("last_maintenance", models.DateField(blank=True, null=True)),
                ("next_maintenance", models.DateField(blank=True, null=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="railway.railwaysection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                ("date", models.DateField()),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="railway.railwaysection",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="railway.train",
                    ),
                ),
            ],
            options={
                "ordering": ["arrival_time"],
                "indexes": [
                    models.Index(
                        fields=["section", "date"],
                        name="railway_tra_section_150b46_idx",
                    )
                ],
            },
        ),
    ]
