# Generated by Django 5.2.6 on 2026-09-09 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsTrainForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expected_train_count', models.PositiveIntegerField()),
                ('forecast_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=8)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_forecasts', to='railway.railwaysection')),
            ],
            options={
                'ordering': ['date', 'section'],
                'indexes': [models.Index(fields=['section', 'date'], name='railway_goo_section_31e9a9_idx')],
                'constraints': [models.UniqueConstraint(fields=('date', 'section'), name='unique_goods_forecast_per_section_date')],
            },
        ),
    ]
