# Generated by Django 5.2.6 on 2026-09-09 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        ("railway", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATED", "Generated"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("MODIFIED", "Modified"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING_APPROVAL",
                        max_length=20,
                    ),
                ),
                ("priority_score", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "utilization",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="block_plans",
                        to="railway.railwaysection",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="BlockPlanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planning.blockplan",
                    ),
                ),
                (
                    "maintenance_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.maintenancetask",
                    ),
                ),
            ],
            options={
                "unique_together": {("block_plan", "maintenance_task")},
            },
        ),
        migrations.AddField(
            model_name="blockplan",
            name="tasks",
            field=models.ManyToManyField(
                related_name="block_plans",
                through="planning.BlockPlanTask",
                to="maintenance.maintenancetask",
            ),
        ),
        migrations.CreateModel(
            name="Conflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("conflict_type", models.CharField(max_length=40)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="planning.blockplan",
                    ),
                ),
                (
                    "block_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="maintenance.blockrequest",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="blockplan",
            index=models.Index(
                fields=["section", "start_time"], name="planning_bl_section_c288c8_idx"
            ),
        ),
    ]
