# Generated by Django 5.2.6 on 2026-09-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_start", models.DateTimeField()),
                ("requested_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PLANNED", "Planned"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExecutionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actual_start", models.DateTimeField()),
                ("actual_end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("DELAYED", "Delayed"),
                            ("CANCELLED", "Cancelled"),
                            ("PARTIAL", "Partially Completed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(max_length=160)),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("ENGINEERING", "Engineering"),
                            ("TRACTION", "Traction"),
                            ("S_AND_T", "S&T"),
                        ],
                        max_length=20,
                    ),
                ),
                ("criticality", models.PositiveSmallIntegerField(default=3)),
                ("urgency", models.PositiveSmallIntegerField(default=3)),
                ("safety_risk", models.PositiveSmallIntegerField(default=3)),
                ("asset_impact", models.PositiveSmallIntegerField(default=3)),
                (
                    "estimated_duration",
                    models.PositiveIntegerField(help_text="Minutes"),
                ),
                ("preferred_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REQUESTED", "Block Requested"),
                            ("PLANNED", "Planned"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "ordering": ["preferred_date", "task_id"],
            },
        ),
    ]
