# Generated by Django 5.2.6 on 2026-09-09 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maintenance", "0001_initial"),
        ("planning", "0001_initial"),
        ("railway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionrecord",
            name="block_plan",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution",
                to="planning.blockplan",
            ),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="railway.asset",
            ),
        ),
        migrations.AddField(
            model_name="maintenancetask",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="railway.railwaysection",
            ),
        ),
        migrations.AddField(
            model_name="blockrequest",
            name="maintenance_task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="block_requests",
                to="maintenance.maintenancetask",
            ),
        ),
    ]
