import { ArrowRight, FlaskConical } from "lucide-react";
import { useEffect, useState } from "react";
import { api, formatDateTime, list } from "../services/api";
import { Badge, Button, Card, EmptyState, ErrorState, Field, inputClass, LoadingState, StatCard } from "../components/ui";

export default function WhatIf() {
  const [plans,setPlans]=useState(null),[planId,setPlanId]=useState(""),[form,setForm]=useState({train_delay:30,duration_change:0,start_shift:0}),[result,setResult]=useState(null),[error,setError]=useState("");
  const role=JSON.parse(localStorage.getItem("railnexus_user")||"{}").role;
  const canControl=["ADMIN","CONTROL_OFFICE"].includes(role);
  useEffect(()=>{list("block-plans").then(p=>{setPlans(p);if(p[0])setPlanId(String(p[0].id))}).catch(e=>setError(e.message))},[]);
  async function simulate(){setError("");try{setResult(await api("/planning/simulate/",{method:"POST",body:JSON.stringify({...form,plan_id:planId})}))}catch(e){setError(e.message)}}
  async function apply(){try{await api(`/block-plans/${planId}/review/`,{method:"POST",body:JSON.stringify({decision:"modify",changes:{start_time:result.after.start,end_time:result.after.end,reason:"What-if scenario reviewed and applied by operator."}})});setResult({...result,applied:true})}catch(e){setError(e.data?.conflicts?.map(c=>c.description).join(" ")||e.message)}}
  if(!canControl)return <ErrorState message="What-if planning actions require Control Office or Admin access."/>;if(error&&!plans)return <ErrorState message={error}/>;if(!plans)return <LoadingState/>;if(!plans.length)return <EmptyState message="Generate a block plan before running a scenario."/>;
  return <div className="space-y-6"><Card title="What-If Scenario Controls"><div className="grid items-end gap-4 md:grid-cols-4"><Field label="Block plan"><select className={inputClass} value={planId} onChange={e=>{setPlanId(e.target.value);setResult(null)}}>{plans.map(p=><option value={p.id} key={p.id}>#{p.id} · {p.section_name}</option>)}</select></Field><Field label="Train delay (minutes)"><input type="number" className={inputClass} value={form.train_delay} onChange={e=>setForm({...form,train_delay:Number(e.target.value)})}/></Field><Field label="Task duration change"><input type="number" className={inputClass} value={form.duration_change} onChange={e=>setForm({...form,duration_change:Number(e.target.value)})}/></Field><Field label="Block start shift"><input type="number" className={inputClass} value={form.start_shift} onChange={e=>setForm({...form,start_shift:Number(e.target.value)})}/></Field></div><Button className="mt-5" onClick={simulate}><FlaskConical className="mr-2 inline" size={17}/>Run simulation</Button><p className="mt-3 text-xs text-slate-500">Simulation is read-only until “Apply Scenario” is selected.</p></Card>{error&&<ErrorState message={error} retry={()=>setError("")}/>}
    {result&&<><div className="grid items-stretch gap-5 lg:grid-cols-[1fr_auto_1fr]"><Scenario title="Before" data={result.before}/><div className="grid place-items-center text-rail-700"><ArrowRight size={30}/></div><Scenario title="After" data={result.after}/></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Conflict change" value={`${result.before.conflicts} → ${result.after.conflicts}`}/><StatCard label="Availability change" value={`${result.before.availability}% → ${result.after.availability}%`}/><StatCard label="Utilization change" value={`${result.before.utilization}% → ${result.after.utilization}%`}/><StatCard label="Projected completed tasks" value={`${result.before.tasks_completed} → ${result.after.tasks_completed}`}/></div>{result.conflict_details.length>0&&<Card title="Scenario Conflicts"><div className="space-y-2">{result.conflict_details.map((c,i)=><p key={i} className="rounded-lg bg-red-50 p-3 text-sm text-red-800"><Badge>{c.severity}</Badge> <span className="ml-2">{c.description}</span></p>)}</div></Card>}<Button disabled={result.applied||result.after.conflicts>0} onClick={apply}>{result.applied?"Scenario Applied":result.after.conflicts>0?"Resolve Scenario Conflicts":"Apply Scenario"}</Button></>}
  </div>;
}
function Scenario({title,data}){return <Card title={title}><p className="font-bold text-rail-950">{formatDateTime(data.start)}</p><p className="text-sm text-slate-500">to {formatDateTime(data.end)}</p><div className="mt-5 flex gap-2"><Badge>{data.conflicts?"CONFLICT":"CLEAR"}</Badge><Badge>{data.utilization}% UTILIZATION</Badge></div></Card>}
